win32_io.c: undefine all enum constants
Some of the STATUS enum constants conflict with those from winnt.h.
This change undefines all of them to be safe.

Fixes compiler error:

In file included from /usr/include/w32api/minwindef.h:163,
                 from /usr/include/w32api/windef.h:9,
                 from /usr/include/w32api/windows.h:69,
                 from win32_io.c:31:
win32_io.c:132:4: error: expected identifier before '(' token
  132 |    STATUS_INVALID_HANDLE =       0xC0000008,
      |    ^~~~~~~~~~~~~~~~~~~~~