win32_io.c: rm GUID type definition
This conflicts with the GUID defined in the Windows headers, and we don't seem to use this one.

Fixes compiler error (could also be fixed by redefining Windows' GUID):

win32_io.c:55:3: error: conflicting types for 'GUID'; have 'struct <anonymous>'
   55 | } GUID;
      |   ^~~~
In file included from /usr/include/w32api/winnt.h:648,
                 from /usr/include/w32api/minwindef.h:163,
                 from /usr/include/w32api/windef.h:9,
                 from /usr/include/w32api/windows.h:69,
                 from win32_io.c:31:
/usr/include/w32api/guiddef.h:24:3: note: previous declaration of 'GUID' with type 'GUID'
   24 | } GUID;
      |   ^~~~